### PR TITLE
Add precinct and private note endpoints

### PR DESCRIPTION
**Pull request by codealchemy**
This adds the specs for the index/crud operations for the precinct endpoint, as well as creating private notes on a person in a nation.

@ccollins

### CODE REVIEW

**Comment by ccollins** [comment]
@codealchemy Specs and code looks good.  Is there any way to actually test this before deploying to production?

**Comment by codealchemy** [comment]
@ccollins I tested it locally with nationbuilder-rb :

``` ruby
client.call(:people, :private_note_create, id: 12345, note: { content: 'Private note content })
```

``` ruby
client.call(:precincts, :index) 
```

and the API Explorer:

screen shot 2015-07-22 at 21 34 52
screen shot 2015-07-22 at 21 35 01

Also did some [cURL requests](https://gist.github.com/codealchemy/253e6fa929fd1d72a08b) that hit those endpoints as well.

**Comment by kitchen** [comment]
Is this supposed to be a public repo?

-Jeremy

## 

Insert PGP signature here.

**Comment by ccollins** [comment]
@kitchen hai!

I don't see any reason it should be private.

**Comment by codealchemy** [comment]
Hey @kitchen !

This is the spec that feeds our ruby client [nationbuilder-rb](https://github.com/nationbuilder/nationbuilder-rb/tree/master/lib/api_spec) and other services using the API to generate their endpoints. There is a [script](https://github.com/nationbuilder/nationbuilder-rb/blob/master/update_subtree.sh#L1) in each that pulls from this repo for updates made, and is public so other folks can do the same.

**Comment by kitchen** [comment]
Ok cool. I just need to unsubscribe from the repo is all then. No worries!

-Jeremy

## 

Insert PGP signature here.

**Pull request merged**
